# Generated by Django 4.2.7 on 2023-11-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("age_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedimage",
            old_name="age",
            new_name="predicted_age",
        ),
        migrations.RenameField(
            model_name="uploadedimage",
            old_name="gender",
            new_name="predicted_gender",
        ),
    ]
