# Generated by Django 4.2.7 on 2023-11-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                ("predicted_age", models.CharField(max_length=100)),
                ("predicted_gender", models.CharField(max_length=100)),
            ],
        ),
    ]
